version: "3.8"

services:
  api-golang:
    ports:
      - "8080:8000"
    env_file:
      - ".env"
    networks:
      - backend
    depends_on:
      - db
    image: danilkompaniets/rss-feed-go


  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgresDb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  postgresDb:

networks:
  backend: